src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{
    
    const HEAT = [
        0 => 'électrique',
        1 => 'gaz'
    ];
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;
    
    function __construct() {
        $this->create_at = new \DateTime();
    }

        public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string {
        
        return (new Slugify())->slugify($this->title);
        
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    
    public function getHeatType(): string {
        
        return self::HEAT[$this->heat];
    }
}

src/Controller/HomeController.php
<?php
namespace App\Controller;

use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
//use Twig\Environment;

/**
 * Description of HomeController
 *
 * @author 91GA003
 */
class HomeController extends AbstractController {
    
// commenter par l'utilisation de AbstractController
//    /**
//     *
//     * @var Environment
//     */
//    private $twig;
//
//
//    public function __construct(Environment $twig) {
//        $this->twig = $twig;
//    }
//
    /**
     * @Route("/", name="home")
     * @param PropertyRepository $repository
     * @return Response
     */
    public function index(PropertyRepository $repository): Response{
        
        $properties = $repository->findLastest();
//        return new Response($this->twig->render('pages/home.html.twig'));
        return $this->render('pages/home.html.twig', ['properties' => $properties]);
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
/**
 * Description of PropertyController
 *
 * @author didier
 */
class PropertyController extends AbstractController {

    /**
     * @var EntityManagerInterface
     */
    private $em;

    /**
     * @var PropertyRepository
     */
    private $repository;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em) {
        
        $this->repository = $repository;
        $this->em = $em;
    }

    
    /**
     * @route("/biens", name="property.index")
     * @return Response
     */
    public function index(): Response{
        
// commenter après la création en base du premier bien
//        $property = new Property();
//        $property->setTitle('Mon premier bien')
//                ->setPrice(200000)
//                ->setRooms(4)
//                ->setBedrooms(3)
//                ->setDescription('Une petite description')
//                ->setSurface(60)
//                ->setFloor(4)
//                ->setHeat(1)
//                ->setCity('Créteil')
//                ->setAddress('9 rue Marc Seguin')
//                ->setPostalCode('94000');
//        $em = $this->getDoctrine()->getManager();
//        $em->persist($property);
//        $em->flush();
        
    //    $property = $this->repository->findAllVisible();
    //    $property[0]->setSold(true);
//        $em = $this->getDoctrine()->getManager();
//        $em->flush();
    //    $this->em->flush();
        return $this->render('property/index.html.twig',
                ['current_menu' => 'properties']);
    }
    
    /**
     * @route("/biens/{slug}.{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @return Response
     */
    public function show(Property $property, string $slug): Response {
    //public function show($slug, $id): Response {    
    //    $property = $this->repository->find($id);
        if ($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show',
                    [
                        'id' => $property->getId(),
                        'slug' => $property->getSlug()
                    ], 301);    // rediection permanente
        }
        return $this->render('property/show.html.twig',
           ['property' => $property,
            'current_menu' => 'properties'
           ]); 
 
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="{{ path('home') }}">Mon Agence</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if(current_menu is defined and current_menu == 'properties') %}active{% endif %}" href="{{ path('property.index') }}">Acheter</a>
                    </li>
                </ul>
            </div>
        </nav>

        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

templates/pages/home.html.twig
{% extends "base.html.twig" %}

{% block title 'Mon Agence' %}

{% block body %}
    
    <div class="jumbotron text-center">
        <h1>Agense DWWM</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam iaculis
            nunc a vehicula bibendum. Integer vestibulum laoreet consectetur.
            Nam porta lacus vitae massa vehicula condimentum. </p>
    </div>
    
    <div class="container">
        <h2>Les derniers biens</h2>
        <div class="row flex">
            {% for property in properties %}
                <div class="col-3">
                    <div class="card">
                        <div class="card-boby">
                            <h5 class="card_title">
                                <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.title }}</a>
                            </h5>
                            <p class="card-text">{{ property.city }} ({{ property.postalCode }})</p>
                            <div class="text-primary" style="font-weight: bold; font-size: 2rem;">{{ property.formatedPrice }} €</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    
{% endblock %}

templates/property/index.html.twig
{%  extends "base.html.twig" %}

{% block title 'Tous nos biens' %}
    
{% block body %}
    
    <div class="container mt-4">
        <h1>Voir tous nos biens</h1>
    </div>
    
{% endblock %}

templates/property/show.html.twig
{%  extends "base.html.twig" %}

{% block title property.title %}

    {% block body %}

        <div class="jumbotron">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">

                    </div>
                    <div class="col-md-4">
                        <h1>{{ property.title }}</h1>
                        <h2>{{ property.rooms }} pièces . {{ property.surface }} m2</h2>
                        <div class="text-primary" style="font-weight: bold; font-size: 4rem">{{ property.formatedPrice }} €</div>
                        <a href="#" class="btn btn-primary">Contacter l'agence</a>
                    </div>
                </div>
            </div>
        </div>
                        
        <div class="container mt-4">
            <p>
                {{ property.description | nl2br }}
            </p>

            <div class="row">
                <div class="col-md-8">
                    <h2>Caractéristiques</h2>
                    <table class="table table-striped">
                        <tr>
                            <td>Surface habitable</td>
                            <td>{{ property.surface }} m2</td>
                        </tr>
                        <tr>
                            <td>Pièces</td>
                            <td>{{ property.rooms }} m2</td>
                        </tr>
                        <tr>
                            <td>Surface habitable</td>
                            <td>{{ property.surface }} m2</td>
                        </tr>
                        <tr>
                            <td>Chambres</td>
                            <td>{{ property.bedRooms }} m2</td>
                        </tr>
                        <tr>
                            <td>Etage</td>
                            <td>{{ property.floor }} m2</td>
                        </tr>
                        <tr>
                            <td>Chauffage</td>
                            <td>{{ property.heatType }} m2</td>
                        </tr>
                    </table>
                </div>
                <div class="col-md-4">
                    <h2>Spécificités</h2>
                </div>
            </div>

        {% endblock %}